# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Publish
      run: dotnet publish API --configuration Release --self-contained --artifacts-path publish/ -r linux-arm -p:PublishSingleFile=true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        path: "publish/publish/API/release_linux-arm/*"